#
# @see https://github.com/rectorphp/rector
#

name: Refactor (Rector)

on:
  workflow_call:
    inputs:
      commit_message:
        description: 'Commit message.'
        required: false
        default: 'refactor: code quality assurance'
        type: string
      config_file:
        description: 'Rector config file. [default: "rector.php"]'
        required: false
        default: 'rector.php'
        type: string
      rector_version:
        description: 'Rector version.'
        required: false
        default: '0.18.5'
        type: string
      rector_laravel_version:
        description: 'Rector Laravel plugin version.'
        required: false
        default: '0.26.1'
        type: string

permissions:
  contents: write

jobs:
  refactor:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rector
        run: composer global require rector/rector:${{ inputs.rector_version }} driftingly/rector-laravel:${{ inputs.rector_laravel_version }} --dev --no-progress

      - name: Run Rector
        run: /tmp/vendor/bin/rector process --config ${{ inputs.config_file }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.commit_message }}

