#
# @see https://github.com/rectorphp/rector
#

name: Refactor (Rector)

on:
  workflow_call:
    inputs:
      commit_message:
        description: 'Commit message.'
        required: false
        default: 'refactor: code quality assurance'
        type: string
      config_file:
        description: 'Rector config file. [default: "rector.php"]'
        required: false
        default: 'rector.php'
        type: string
      rector_version:
        description: 'Rector version.'
        required: false
        default: '0.18.5'
        type: string

permissions:
  contents: write

jobs:
  refactor:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Rector
        uses: zingimmick/rector-action@0.0.3
        with:
          version: ${{ inputs.rector_version }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.commit_message }}

